/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.apache.kafka:kafka-clients:2.1.1")
    api("org.slf4j:slf4j-api:1.7.25")
    implementation("ch.qos.logback:logback-classic:1.2.9")
    testImplementation("com.carrotsearch:junit-benchmarks:0.7.2")
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.hamcrest:hamcrest-all:1.3")
    testImplementation("org.apache.kafka:kafka_2.11:2.1.1")
    testImplementation("org.apache.zookeeper:zookeeper:3.4.14")
    testImplementation("org.slf4j:log4j-over-slf4j:1.7.25")
    testImplementation("org.mockito:mockito-core:2.23.4")
}

group = "com.github.danielwegener"
version = "0.2.0-SNAPSHOT"
description = "logback-kafka-appender"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
